version: '3.7'
services:
  nodejs:
    build:
      context: ./cds-services-manager/
      dockerfile: Dockerfile
    image: road2h-dmims
    container_name: services_manager_service
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - PORT=3010
      - LOGS=cds_sm_logs
      - MONGODB_TEMPLATES=templates
      - MONGODB_CIG_MODEL=tmr
      - INTERACTION_HOST=tmrweb
      - INTERACTION_PORT=8888
      - INTERACTION_DB=tmrweb
      - ARGUMENTATION_PORT=5000
      - ARGUMENTATION_HOST=localhost
    depends_on: 
      - db
    networks:
      - dmims
      - tmrwebx_cig_handler
    #command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
  db:
    image: mongo:4.4.17
    restart: unless-stopped
    ports: 
        - "27017:27017"
    container_name: mongodb
    volumes:
      - ~/mongodata:/data/db
    networks:
      - dmims
      - mongodb_network
  mongo-seed:
        build:
            context: ./MongoDB_templates
            dockerfile: Dockerfile
            args:
                - MONGODB_PORT=27017
        depends_on:
            - db
        networks:
            - mongodb_network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - db
    networks:
    - mongodb_network
    ports:
    - 8081:8081
#external_links: 
#  - tmrweb
networks:
  dmims: {}
 # tmrwebx_cig_handler: {} #intercommunication with TMRwebX
  mongodb_network: {}
 # cig_interaction: {} #intercommunication with TMRwebX (alternative)
volumes: 
 mongodata:
   name: mongodata